import { describe, expect, it } from 'vitest'
import { createMemoryHistory, createRouter } from 'vue-router'
import { routes } from 'vue-router/auto-routes'
import declaration from '@/typed-router.d.ts?raw'

// A smoke test over every generated route.
//
// `anzu-local/valid-route-name` already checks that a name referenced in the code exists. It
// cannot check that the route behind it can be reached: a path whose constraint never matches,
// or one shadowed by an earlier record, still has a perfectly valid name. Navigating to it lands
// on the catch-all instead, which renders a 404 page and throws nothing -- so a broken route
// looks exactly like a working one until somebody clicks it.
//
// Importing `vue-router/auto-routes` is itself half the test: it pulls in every page component
// and, through them, their stores, api clients and composables, so anything that throws while a
// module is evaluated fails here. That half depends on `importMode` being `sync`, which the
// vitest config pins -- `routerPages` alone would switch to `async` under NODE_ENV=production and
// leave the components as thunks nobody awaits.

const CATCH_ALL = 'pathMatch'

// The declaration holds TypeScript source, so a `\d` constraint is written there as an escaped
// backslash. Reading it raw would leave `\\d`, which matches a literal backslash and nothing else.
const declaredPaths = [...declaration.matchAll(/'[^']+':\s*RouteRecordInfo<\s*'([^']*)',\s*'([^']+)'/g)]
  .map(([, name, path]) => ({ name, path: path.replace(/\\\\/g, '\\') }))
  .filter(({ path }) => !path.includes(CATCH_ALL))

const router = createRouter({ history: createMemoryHistory(), routes })

// `:id(\d+)` has to be filled with something the constraint accepts, or the route would fail to
// match for a reason that says nothing about the route itself.
const fillParams = (path: string) =>
  path.replace(/:[a-zA-Z]+\(\\d\+\)/g, '1').replace(/:[a-zA-Z]+(\([^)]*\))?/g, 'sample')

describe('generated routes', () => {
  it('declares exactly the pages that exist on disk', () => {
    // A guard on the guard: if the declaration were missing or the regex stopped matching, every
    // assertion below would iterate an empty list and pass while checking nothing. Counted from
    // disk rather than against a literal, so it cannot go stale as pages are added or removed --
    // the one page file `declaredPaths` filters out is the catch-all.
    const pageFiles = import.meta.glob('../pages/**/*.vue')
    expect(declaredPaths.length).toBe(Object.keys(pageFiles).length - 1)
  })

  it.each(declaredPaths)('resolves $path to its own record, not the catch-all', ({ name, path }) => {
    const resolved = router.resolve(fillParams(path))

    expect(resolved.matched.some((record) => record.path.includes(CATCH_ALL))).toBe(false)
    expect(resolved.name).toBe(name)
  })

  it('has a runtime route for every declared one, and nothing extra', () => {
    // The declaration is generated from the same scan as `routes`, but they are two artifacts and
    // only one of them is regenerated by `yarn generate:dts`. A stale declaration is exactly the
    // state in which the assertions above would check routes the app no longer has.
    //
    // `router.getRoutes()` rather than `routes`: nested pages are children, so the raw array holds
    // `/blogs/[id]` but not the `/blogs/[id]/edit` underneath it.
    //
    // Worth knowing when this fails locally and not in CI: a dev server left running watches
    // `src/pages` and rewrites the declaration the moment a page file changes, which hides the
    // mismatch this asserts. In CI nothing watches, and `generate:dts` runs before the tests.
    const runtime = new Set(
      router
        .getRoutes()
        .map((route) => route.name)
        .filter((name): name is string => typeof name === 'string')
    )
    const declared = new Set(declaredPaths.map(({ name }) => name))

    expect([...declared].filter((name) => !runtime.has(name))).toEqual([])
    expect([...runtime].filter((name) => !declared.has(name) && !name.includes(CATCH_ALL))).toEqual([])
  })

  it('gives every route a component to render', () => {
    const withoutComponent = router
      .getRoutes()
      .filter((route) => !route.components || Object.keys(route.components).length === 0)

    expect(withoutComponent.map((route) => route.path)).toEqual([])
  })
})
