# Anzu-Admin-DAM project Azure Pipelines Continuous Deployment definition
# 1. Checkout branch to build
# 2. Build the anzu-admin-dam artifact
# 4. Deploy to chosen environment

name: $(rev:rrrr)$(ENVIRONMENT_TAG)

# Disable automatic pipeline trigger
trigger: none

# Setup runtime parameters
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: 'devel'
    values:
      - devel
      - stage

# Setup variables
variables:
  - group: 'admin-dam-${{ parameters.environment }}'
  # Application project name
  - name: APP_NAME
    value: 'admin-dam'
  # Pipeline name shortcuts
  - name: ENVIRONMENT_TAG
    value: '_${{ parameters.environment }}'
  # Application version
  - name: VERSION
    value: '$(Build.SourceBranchName)'

# Checkout azure ci template repository
resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/azure-ci-template

# Pipeline definition
extends:
  template: node-deploy-cfpages.yaml@templates
  parameters:
    containerDockerImageVersion: 'node18'
    yarnWorkDirs:
      - name: root
        path: '.'
    environment: ${{ parameters.environment }}
    prepareConfig: true
    sendAnzuDeployNotification: true
