services:
  app:
    build:
      args:
        - DOCKER_USER=${DOCKER_USER:-node}
        - DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}
      context: .
      dockerfile: ./docker/app/local/Dockerfile
    environment:
      - VIRTUAL_HOST=admin-dam.anzusystems.local
      - VIRTUAL_PORT=8080
    external_links:
      - local-proxy:core-dam.anzusystems.local
      - local-proxy:admin-dam.anzusystems.local
      - local-proxy:notification-server.anzusystems.local
    env_file:
      - .env.docker.dist
      - .env.docker.local
    volumes:
      - .:/var/www/html:cached
    ports:
      - ${DOCKER_VUE_DEV_PORT:-8150}:${DOCKER_VUE_DEV_PORT:-8150}
      - ${NGINX_PORT:-8151}:8080
    hostname: admin-dam.anzusystems.local
    privileged: true
    networks:
      anzusystems_network:
        aliases:
          - admin-dam

networks:
  anzusystems_network:
    external: true
