export const RAND_NUM = `${Cypress._.random(10000, 99999)}`
export const LENGUAGE_SK = 'Slovensky'
export const LENGUAGE_EN = 'English'
export const THEME_LIGHT = 'Light'
export const THEME_DARK = 'Dark'
export const THEME_AUTO = 'Auto'
export const USER_EMAIL = `test.mail+${RAND_NUM}@adam.com`
export const USER_FIRST_NAME = `First${RAND_NUM}`
export const USER_LAST_NAME = `Last${RAND_NUM}`
export const USER_PASSWORD = `pwd${RAND_NUM}`
export const USER_LICENCE = ['CMS system - 1', 'Blog system - 3', 'Blog system - 2']
export const EXTERNAL_SYS = ['cms', 'blog']
export const EXTERNAL_PROVIDER = 'Unsplash'
export const DISTRIBUTION_SERVICE = ['Youtube CMS', 'Youtube Fičí', 'JwVideo', 'Artemis CMS', 'Custom CMS']
export const PERMISSION_GROUP_TITLE = `TestGroup${RAND_NUM}`
export const PODCAST_TITLE = `TestPodcast${RAND_NUM}`
export const PERMISSION_GROUP = `TestGroup${RAND_NUM}`
