/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(common)/anzu-user': RouteRecordInfo<
      '/(common)/anzu-user',
      '/anzu-user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/anzu-user/[id]': RouteRecordInfo<
      '/(common)/anzu-user/[id]',
      '/anzu-user/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/anzu-user/[id]/edit': RouteRecordInfo<
      '/(common)/anzu-user/[id]/edit',
      '/anzu-user/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/log': RouteRecordInfo<
      '/(common)/log',
      '/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/log/[system]/[type]/[id]': RouteRecordInfo<
      '/(common)/log/[system]/[type]/[id]',
      '/log/:system/:type/:id',
      { system: ParamValue<true>, type: ParamValue<true>, id: ParamValue<true> },
      { system: ParamValue<false>, type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/(common)/permission-group': RouteRecordInfo<
      '/(common)/permission-group',
      '/permission-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/permission-group/[id]': RouteRecordInfo<
      '/(common)/permission-group/[id]',
      '/permission-group/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/permission-group/[id]/edit': RouteRecordInfo<
      '/(common)/permission-group/[id]/edit',
      '/permission-group/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset': RouteRecordInfo<
      '/(coreDam)/asset',
      '/asset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/asset/[id]': RouteRecordInfo<
      '/(coreDam)/asset/[id]',
      '/asset/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset/file/[id]': RouteRecordInfo<
      '/(coreDam)/asset/file/[id]',
      '/asset/file/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence': RouteRecordInfo<
      '/(coreDam)/asset-licence',
      '/asset-licence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/asset-licence/[id]': RouteRecordInfo<
      '/(coreDam)/asset-licence/[id]',
      '/asset-licence/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence/[id]/edit': RouteRecordInfo<
      '/(coreDam)/asset-licence/[id]/edit',
      '/asset-licence/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence-group': RouteRecordInfo<
      '/(coreDam)/asset-licence-group',
      '/asset-licence-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/asset-licence-group/[id]': RouteRecordInfo<
      '/(coreDam)/asset-licence-group/[id]',
      '/asset-licence-group/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence-group/[id]/edit': RouteRecordInfo<
      '/(coreDam)/asset-licence-group/[id]/edit',
      '/asset-licence-group/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author': RouteRecordInfo<
      '/(coreDam)/author',
      '/author',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/author/[id]': RouteRecordInfo<
      '/(coreDam)/author/[id]',
      '/author/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author/[id]/edit': RouteRecordInfo<
      '/(coreDam)/author/[id]/edit',
      '/author/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author-clean-phrase': RouteRecordInfo<
      '/(coreDam)/author-clean-phrase',
      '/author-clean-phrase',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/author-clean-phrase/[id]': RouteRecordInfo<
      '/(coreDam)/author-clean-phrase/[id]',
      '/author-clean-phrase/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author-clean-phrase/[id]/edit': RouteRecordInfo<
      '/(coreDam)/author-clean-phrase/[id]/edit',
      '/author-clean-phrase/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category': RouteRecordInfo<
      '/(coreDam)/distribution-category',
      '/distribution-category',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/distribution-category/[id]': RouteRecordInfo<
      '/(coreDam)/distribution-category/[id]',
      '/distribution-category/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category/[id]/edit': RouteRecordInfo<
      '/(coreDam)/distribution-category/[id]/edit',
      '/distribution-category/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category-select': RouteRecordInfo<
      '/(coreDam)/distribution-category-select',
      '/distribution-category-select',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/distribution-category-select/[id]': RouteRecordInfo<
      '/(coreDam)/distribution-category-select/[id]',
      '/distribution-category-select/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category-select/[id]/edit': RouteRecordInfo<
      '/(coreDam)/distribution-category-select/[id]/edit',
      '/distribution-category-select/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/ext-system': RouteRecordInfo<
      '/(coreDam)/ext-system',
      '/ext-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/ext-system/[id]': RouteRecordInfo<
      '/(coreDam)/ext-system/[id]',
      '/ext-system/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/ext-system/[id]/edit': RouteRecordInfo<
      '/(coreDam)/ext-system/[id]/edit',
      '/ext-system/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/external-provider/[provider]': RouteRecordInfo<
      '/(coreDam)/external-provider/[provider]',
      '/external-provider/:provider',
      { provider: ParamValue<true> },
      { provider: ParamValue<false> },
      | never
    >,
    '/(coreDam)/job': RouteRecordInfo<
      '/(coreDam)/job',
      '/job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/job/[id]': RouteRecordInfo<
      '/(coreDam)/job/[id]',
      '/job/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/keyword': RouteRecordInfo<
      '/(coreDam)/keyword',
      '/keyword',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/keyword/[id]': RouteRecordInfo<
      '/(coreDam)/keyword/[id]',
      '/keyword/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/keyword/[id]/edit': RouteRecordInfo<
      '/(coreDam)/keyword/[id]/edit',
      '/keyword/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcast': RouteRecordInfo<
      '/(coreDam)/podcast',
      '/podcast',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/podcast/[id]': RouteRecordInfo<
      '/(coreDam)/podcast/[id]',
      '/podcast/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcast/[id]/edit': RouteRecordInfo<
      '/(coreDam)/podcast/[id]/edit',
      '/podcast/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcast/[id]/episode/[episodeId]': RouteRecordInfo<
      '/(coreDam)/podcast/[id]/episode/[episodeId]',
      '/podcast/:id/episode/:episodeId',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcast/[id]/episode/[episodeId]/edit': RouteRecordInfo<
      '/(coreDam)/podcast/[id]/episode/[episodeId]/edit',
      '/podcast/:id/episode/:episodeId/edit',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/public-export': RouteRecordInfo<
      '/(coreDam)/public-export',
      '/public-export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/public-export/[id]': RouteRecordInfo<
      '/(coreDam)/public-export/[id]',
      '/public-export/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/public-export/[id]/edit': RouteRecordInfo<
      '/(coreDam)/public-export/[id]/edit',
      '/public-export/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/user': RouteRecordInfo<
      '/(coreDam)/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/user/[id]': RouteRecordInfo<
      '/(coreDam)/user/[id]',
      '/user/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/user/[id]/edit': RouteRecordInfo<
      '/(coreDam)/user/[id]/edit',
      '/user/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-show': RouteRecordInfo<
      '/(coreDam)/video-show',
      '/video-show',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/video-show/[id]': RouteRecordInfo<
      '/(coreDam)/video-show/[id]',
      '/video-show/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-show/[id]/edit': RouteRecordInfo<
      '/(coreDam)/video-show/[id]/edit',
      '/video-show/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-show/[id]/episode/[episodeId]': RouteRecordInfo<
      '/(coreDam)/video-show/[id]/episode/[episodeId]',
      '/video-show/:id/episode/:episodeId',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-show/[id]/episode/[episodeId]/edit': RouteRecordInfo<
      '/(coreDam)/video-show/[id]/episode/[episodeId]/edit',
      '/video-show/:id/episode/:episodeId/edit',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...pathMatch]': RouteRecordInfo<
      '/[...pathMatch]',
      '/:pathMatch(.*)',
      { pathMatch: ParamValue<true> },
      { pathMatch: ParamValue<false> },
      | never
    >,
    '/close-page': RouteRecordInfo<
      '/close-page',
      '/close-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout': RouteRecordInfo<
      '/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/unauthorized': RouteRecordInfo<
      '/unauthorized',
      '/unauthorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(common)/anzu-user/index.vue': {
      routes:
        | '/(common)/anzu-user'
      views:
        | never
    }
    'src/pages/(common)/anzu-user/[id]/index.vue': {
      routes:
        | '/(common)/anzu-user/[id]'
      views:
        | never
    }
    'src/pages/(common)/anzu-user/[id]/edit.vue': {
      routes:
        | '/(common)/anzu-user/[id]/edit'
      views:
        | never
    }
    'src/pages/(common)/log/index.vue': {
      routes:
        | '/(common)/log'
      views:
        | never
    }
    'src/pages/(common)/log/[system]/[type]/[id].vue': {
      routes:
        | '/(common)/log/[system]/[type]/[id]'
      views:
        | never
    }
    'src/pages/(common)/permission-group/index.vue': {
      routes:
        | '/(common)/permission-group'
      views:
        | never
    }
    'src/pages/(common)/permission-group/[id]/index.vue': {
      routes:
        | '/(common)/permission-group/[id]'
      views:
        | never
    }
    'src/pages/(common)/permission-group/[id]/edit.vue': {
      routes:
        | '/(common)/permission-group/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/asset/index.vue': {
      routes:
        | '/(coreDam)/asset'
      views:
        | never
    }
    'src/pages/(coreDam)/asset/[id].vue': {
      routes:
        | '/(coreDam)/asset/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/asset/file/[id].vue': {
      routes:
        | '/(coreDam)/asset/file/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence/index.vue': {
      routes:
        | '/(coreDam)/asset-licence'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence/[id]/index.vue': {
      routes:
        | '/(coreDam)/asset-licence/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence/[id]/edit.vue': {
      routes:
        | '/(coreDam)/asset-licence/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence-group/index.vue': {
      routes:
        | '/(coreDam)/asset-licence-group'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence-group/[id]/index.vue': {
      routes:
        | '/(coreDam)/asset-licence-group/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/asset-licence-group/[id]/edit.vue': {
      routes:
        | '/(coreDam)/asset-licence-group/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/author/index.vue': {
      routes:
        | '/(coreDam)/author'
      views:
        | never
    }
    'src/pages/(coreDam)/author/[id]/index.vue': {
      routes:
        | '/(coreDam)/author/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/author/[id]/edit.vue': {
      routes:
        | '/(coreDam)/author/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/author-clean-phrase/index.vue': {
      routes:
        | '/(coreDam)/author-clean-phrase'
      views:
        | never
    }
    'src/pages/(coreDam)/author-clean-phrase/[id]/index.vue': {
      routes:
        | '/(coreDam)/author-clean-phrase/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/author-clean-phrase/[id]/edit.vue': {
      routes:
        | '/(coreDam)/author-clean-phrase/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category/index.vue': {
      routes:
        | '/(coreDam)/distribution-category'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category/[id]/index.vue': {
      routes:
        | '/(coreDam)/distribution-category/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category/[id]/edit.vue': {
      routes:
        | '/(coreDam)/distribution-category/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category-select/index.vue': {
      routes:
        | '/(coreDam)/distribution-category-select'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category-select/[id]/index.vue': {
      routes:
        | '/(coreDam)/distribution-category-select/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/distribution-category-select/[id]/edit.vue': {
      routes:
        | '/(coreDam)/distribution-category-select/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/ext-system/index.vue': {
      routes:
        | '/(coreDam)/ext-system'
      views:
        | never
    }
    'src/pages/(coreDam)/ext-system/[id]/index.vue': {
      routes:
        | '/(coreDam)/ext-system/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/ext-system/[id]/edit.vue': {
      routes:
        | '/(coreDam)/ext-system/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/external-provider/[provider]/index.vue': {
      routes:
        | '/(coreDam)/external-provider/[provider]'
      views:
        | never
    }
    'src/pages/(coreDam)/job/index.vue': {
      routes:
        | '/(coreDam)/job'
      views:
        | never
    }
    'src/pages/(coreDam)/job/[id].vue': {
      routes:
        | '/(coreDam)/job/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/keyword/index.vue': {
      routes:
        | '/(coreDam)/keyword'
      views:
        | never
    }
    'src/pages/(coreDam)/keyword/[id]/index.vue': {
      routes:
        | '/(coreDam)/keyword/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/keyword/[id]/edit.vue': {
      routes:
        | '/(coreDam)/keyword/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/podcast/index.vue': {
      routes:
        | '/(coreDam)/podcast'
      views:
        | never
    }
    'src/pages/(coreDam)/podcast/[id]/index.vue': {
      routes:
        | '/(coreDam)/podcast/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/podcast/[id]/edit.vue': {
      routes:
        | '/(coreDam)/podcast/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/podcast/[id]/episode/[episodeId]/index.vue': {
      routes:
        | '/(coreDam)/podcast/[id]/episode/[episodeId]'
      views:
        | never
    }
    'src/pages/(coreDam)/podcast/[id]/episode/[episodeId]/edit.vue': {
      routes:
        | '/(coreDam)/podcast/[id]/episode/[episodeId]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/public-export/index.vue': {
      routes:
        | '/(coreDam)/public-export'
      views:
        | never
    }
    'src/pages/(coreDam)/public-export/[id]/index.vue': {
      routes:
        | '/(coreDam)/public-export/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/public-export/[id]/edit.vue': {
      routes:
        | '/(coreDam)/public-export/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/user/index.vue': {
      routes:
        | '/(coreDam)/user'
      views:
        | never
    }
    'src/pages/(coreDam)/user/[id]/index.vue': {
      routes:
        | '/(coreDam)/user/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/user/[id]/edit.vue': {
      routes:
        | '/(coreDam)/user/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/video-show/index.vue': {
      routes:
        | '/(coreDam)/video-show'
      views:
        | never
    }
    'src/pages/(coreDam)/video-show/[id]/index.vue': {
      routes:
        | '/(coreDam)/video-show/[id]'
      views:
        | never
    }
    'src/pages/(coreDam)/video-show/[id]/edit.vue': {
      routes:
        | '/(coreDam)/video-show/[id]/edit'
      views:
        | never
    }
    'src/pages/(coreDam)/video-show/[id]/episode/[episodeId]/index.vue': {
      routes:
        | '/(coreDam)/video-show/[id]/episode/[episodeId]'
      views:
        | never
    }
    'src/pages/(coreDam)/video-show/[id]/episode/[episodeId]/edit.vue': {
      routes:
        | '/(coreDam)/video-show/[id]/episode/[episodeId]/edit'
      views:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...pathMatch].vue': {
      routes:
        | '/[...pathMatch]'
      views:
        | never
    }
    'src/pages/close-page.vue': {
      routes:
        | '/close-page'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/logout.vue': {
      routes:
        | '/logout'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/unauthorized.vue': {
      routes:
        | '/unauthorized'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
