/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(common)/anzu-users': RouteRecordInfo<
      '/(common)/anzu-users',
      '/anzu-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/anzu-users/[id]': RouteRecordInfo<
      '/(common)/anzu-users/[id]',
      '/anzu-users/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/anzu-users/[id]/edit': RouteRecordInfo<
      '/(common)/anzu-users/[id]/edit',
      '/anzu-users/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/logs': RouteRecordInfo<
      '/(common)/logs',
      '/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/logs/[system]/[type]/[id]': RouteRecordInfo<
      '/(common)/logs/[system]/[type]/[id]',
      '/logs/:system/:type/:id',
      { system: ParamValue<true>, type: ParamValue<true>, id: ParamValue<true> },
      { system: ParamValue<false>, type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/(common)/permission-groups': RouteRecordInfo<
      '/(common)/permission-groups',
      '/permission-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(common)/permission-groups/[id]': RouteRecordInfo<
      '/(common)/permission-groups/[id]',
      '/permission-groups/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(common)/permission-groups/[id]/edit': RouteRecordInfo<
      '/(common)/permission-groups/[id]/edit',
      '/permission-groups/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence-groups': RouteRecordInfo<
      '/(coreDam)/asset-licence-groups',
      '/asset-licence-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/asset-licence-groups/[id]': RouteRecordInfo<
      '/(coreDam)/asset-licence-groups/[id]',
      '/asset-licence-groups/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licence-groups/[id]/edit': RouteRecordInfo<
      '/(coreDam)/asset-licence-groups/[id]/edit',
      '/asset-licence-groups/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licences': RouteRecordInfo<
      '/(coreDam)/asset-licences',
      '/asset-licences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/asset-licences/[id]': RouteRecordInfo<
      '/(coreDam)/asset-licences/[id]',
      '/asset-licences/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/asset-licences/[id]/edit': RouteRecordInfo<
      '/(coreDam)/asset-licences/[id]/edit',
      '/asset-licences/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/assets': RouteRecordInfo<
      '/(coreDam)/assets',
      '/assets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/assets/[id]': RouteRecordInfo<
      '/(coreDam)/assets/[id]',
      '/assets/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/assets/file/[id]': RouteRecordInfo<
      '/(coreDam)/assets/file/[id]',
      '/assets/file/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author-clean-phrases': RouteRecordInfo<
      '/(coreDam)/author-clean-phrases',
      '/author-clean-phrases',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/author-clean-phrases/[id]': RouteRecordInfo<
      '/(coreDam)/author-clean-phrases/[id]',
      '/author-clean-phrases/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/author-clean-phrases/[id]/edit': RouteRecordInfo<
      '/(coreDam)/author-clean-phrases/[id]/edit',
      '/author-clean-phrases/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/authors': RouteRecordInfo<
      '/(coreDam)/authors',
      '/authors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/authors/[id]': RouteRecordInfo<
      '/(coreDam)/authors/[id]',
      '/authors/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/authors/[id]/edit': RouteRecordInfo<
      '/(coreDam)/authors/[id]/edit',
      '/authors/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-categories': RouteRecordInfo<
      '/(coreDam)/distribution-categories',
      '/distribution-categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/distribution-categories/[id]': RouteRecordInfo<
      '/(coreDam)/distribution-categories/[id]',
      '/distribution-categories/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-categories/[id]/edit': RouteRecordInfo<
      '/(coreDam)/distribution-categories/[id]/edit',
      '/distribution-categories/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category-selects': RouteRecordInfo<
      '/(coreDam)/distribution-category-selects',
      '/distribution-category-selects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/distribution-category-selects/[id]': RouteRecordInfo<
      '/(coreDam)/distribution-category-selects/[id]',
      '/distribution-category-selects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/distribution-category-selects/[id]/edit': RouteRecordInfo<
      '/(coreDam)/distribution-category-selects/[id]/edit',
      '/distribution-category-selects/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/ext-systems': RouteRecordInfo<
      '/(coreDam)/ext-systems',
      '/ext-systems',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/ext-systems/[id]': RouteRecordInfo<
      '/(coreDam)/ext-systems/[id]',
      '/ext-systems/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/ext-systems/[id]/edit': RouteRecordInfo<
      '/(coreDam)/ext-systems/[id]/edit',
      '/ext-systems/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/external-providers/[provider]': RouteRecordInfo<
      '/(coreDam)/external-providers/[provider]',
      '/external-providers/:provider',
      { provider: ParamValue<true> },
      { provider: ParamValue<false> },
      | never
    >,
    '/(coreDam)/jobs': RouteRecordInfo<
      '/(coreDam)/jobs',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/jobs/[id]': RouteRecordInfo<
      '/(coreDam)/jobs/[id]',
      '/jobs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/keywords': RouteRecordInfo<
      '/(coreDam)/keywords',
      '/keywords',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/keywords/[id]': RouteRecordInfo<
      '/(coreDam)/keywords/[id]',
      '/keywords/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/keywords/[id]/edit': RouteRecordInfo<
      '/(coreDam)/keywords/[id]/edit',
      '/keywords/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcasts': RouteRecordInfo<
      '/(coreDam)/podcasts',
      '/podcasts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/podcasts/[id]': RouteRecordInfo<
      '/(coreDam)/podcasts/[id]',
      '/podcasts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcasts/[id]/edit': RouteRecordInfo<
      '/(coreDam)/podcasts/[id]/edit',
      '/podcasts/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcasts/[id]/episodes/[episodeId]': RouteRecordInfo<
      '/(coreDam)/podcasts/[id]/episodes/[episodeId]',
      '/podcasts/:id/episodes/:episodeId',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/podcasts/[id]/episodes/[episodeId]/edit': RouteRecordInfo<
      '/(coreDam)/podcasts/[id]/episodes/[episodeId]/edit',
      '/podcasts/:id/episodes/:episodeId/edit',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/public-exports': RouteRecordInfo<
      '/(coreDam)/public-exports',
      '/public-exports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/public-exports/[id]': RouteRecordInfo<
      '/(coreDam)/public-exports/[id]',
      '/public-exports/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/public-exports/[id]/edit': RouteRecordInfo<
      '/(coreDam)/public-exports/[id]/edit',
      '/public-exports/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/tts-narration-requests': RouteRecordInfo<
      '/(coreDam)/tts-narration-requests',
      '/tts-narration-requests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/tts-narration-requests/[id]': RouteRecordInfo<
      '/(coreDam)/tts-narration-requests/[id]',
      '/tts-narration-requests/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/users': RouteRecordInfo<
      '/(coreDam)/users',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/users/[id]': RouteRecordInfo<
      '/(coreDam)/users/[id]',
      '/users/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/users/[id]/edit': RouteRecordInfo<
      '/(coreDam)/users/[id]/edit',
      '/users/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-shows': RouteRecordInfo<
      '/(coreDam)/video-shows',
      '/video-shows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/video-shows/[id]': RouteRecordInfo<
      '/(coreDam)/video-shows/[id]',
      '/video-shows/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-shows/[id]/edit': RouteRecordInfo<
      '/(coreDam)/video-shows/[id]/edit',
      '/video-shows/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-shows/[id]/episodes/[episodeId]': RouteRecordInfo<
      '/(coreDam)/video-shows/[id]/episodes/[episodeId]',
      '/video-shows/:id/episodes/:episodeId',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/video-shows/[id]/episodes/[episodeId]/edit': RouteRecordInfo<
      '/(coreDam)/video-shows/[id]/episodes/[episodeId]/edit',
      '/video-shows/:id/episodes/:episodeId/edit',
      { id: ParamValue<true>, episodeId: ParamValue<true> },
      { id: ParamValue<false>, episodeId: ParamValue<false> },
      | never
    >,
    '/(coreDam)/voice-families': RouteRecordInfo<
      '/(coreDam)/voice-families',
      '/voice-families',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(coreDam)/voice-families/[id]': RouteRecordInfo<
      '/(coreDam)/voice-families/[id]',
      '/voice-families/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/(coreDam)/voice-families/[id]/edit': RouteRecordInfo<
      '/(coreDam)/voice-families/[id]/edit',
      '/voice-families/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...pathMatch]': RouteRecordInfo<
      '/[...pathMatch]',
      '/:pathMatch(.*)',
      { pathMatch: ParamValue<true> },
      { pathMatch: ParamValue<false> },
      | never
    >,
    '/close-page': RouteRecordInfo<
      '/close-page',
      '/close-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout': RouteRecordInfo<
      '/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/unauthorized': RouteRecordInfo<
      '/unauthorized',
      '/unauthorized',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(common)/anzu-users/index.vue': {
      routes:
        | '/(common)/anzu-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/anzu-users/[id]/index.vue': {
      routes:
        | '/(common)/anzu-users/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/anzu-users/[id]/edit.vue': {
      routes:
        | '/(common)/anzu-users/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/logs/index.vue': {
      routes:
        | '/(common)/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/logs/[system]/[type]/[id].vue': {
      routes:
        | '/(common)/logs/[system]/[type]/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(common)/permission-groups/index.vue': {
      routes:
        | '/(common)/permission-groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/permission-groups/[id]/index.vue': {
      routes:
        | '/(common)/permission-groups/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(common)/permission-groups/[id]/edit.vue': {
      routes:
        | '/(common)/permission-groups/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licence-groups/index.vue': {
      routes:
        | '/(coreDam)/asset-licence-groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licence-groups/[id]/index.vue': {
      routes:
        | '/(coreDam)/asset-licence-groups/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licence-groups/[id]/edit.vue': {
      routes:
        | '/(coreDam)/asset-licence-groups/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licences/index.vue': {
      routes:
        | '/(coreDam)/asset-licences'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licences/[id]/index.vue': {
      routes:
        | '/(coreDam)/asset-licences/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/asset-licences/[id]/edit.vue': {
      routes:
        | '/(coreDam)/asset-licences/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/assets/index.vue': {
      routes:
        | '/(coreDam)/assets'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/assets/[id].vue': {
      routes:
        | '/(coreDam)/assets/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(coreDam)/assets/file/[id].vue': {
      routes:
        | '/(coreDam)/assets/file/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(coreDam)/author-clean-phrases/index.vue': {
      routes:
        | '/(coreDam)/author-clean-phrases'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/author-clean-phrases/[id]/index.vue': {
      routes:
        | '/(coreDam)/author-clean-phrases/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/author-clean-phrases/[id]/edit.vue': {
      routes:
        | '/(coreDam)/author-clean-phrases/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/authors/index.vue': {
      routes:
        | '/(coreDam)/authors'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/authors/[id]/index.vue': {
      routes:
        | '/(coreDam)/authors/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/authors/[id]/edit.vue': {
      routes:
        | '/(coreDam)/authors/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-categories/index.vue': {
      routes:
        | '/(coreDam)/distribution-categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-categories/[id]/index.vue': {
      routes:
        | '/(coreDam)/distribution-categories/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-categories/[id]/edit.vue': {
      routes:
        | '/(coreDam)/distribution-categories/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-category-selects/index.vue': {
      routes:
        | '/(coreDam)/distribution-category-selects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-category-selects/[id]/index.vue': {
      routes:
        | '/(coreDam)/distribution-category-selects/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/distribution-category-selects/[id]/edit.vue': {
      routes:
        | '/(coreDam)/distribution-category-selects/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/ext-systems/index.vue': {
      routes:
        | '/(coreDam)/ext-systems'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/ext-systems/[id]/index.vue': {
      routes:
        | '/(coreDam)/ext-systems/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/ext-systems/[id]/edit.vue': {
      routes:
        | '/(coreDam)/ext-systems/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/external-providers/[provider]/index.vue': {
      routes:
        | '/(coreDam)/external-providers/[provider]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/jobs/index.vue': {
      routes:
        | '/(coreDam)/jobs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/jobs/[id].vue': {
      routes:
        | '/(coreDam)/jobs/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(coreDam)/keywords/index.vue': {
      routes:
        | '/(coreDam)/keywords'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/keywords/[id]/index.vue': {
      routes:
        | '/(coreDam)/keywords/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/keywords/[id]/edit.vue': {
      routes:
        | '/(coreDam)/keywords/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/podcasts/index.vue': {
      routes:
        | '/(coreDam)/podcasts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/podcasts/[id]/index.vue': {
      routes:
        | '/(coreDam)/podcasts/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/podcasts/[id]/edit.vue': {
      routes:
        | '/(coreDam)/podcasts/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/podcasts/[id]/episodes/[episodeId]/index.vue': {
      routes:
        | '/(coreDam)/podcasts/[id]/episodes/[episodeId]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/podcasts/[id]/episodes/[episodeId]/edit.vue': {
      routes:
        | '/(coreDam)/podcasts/[id]/episodes/[episodeId]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/public-exports/index.vue': {
      routes:
        | '/(coreDam)/public-exports'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/public-exports/[id]/index.vue': {
      routes:
        | '/(coreDam)/public-exports/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/public-exports/[id]/edit.vue': {
      routes:
        | '/(coreDam)/public-exports/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/tts-narration-requests/index.vue': {
      routes:
        | '/(coreDam)/tts-narration-requests'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/tts-narration-requests/[id].vue': {
      routes:
        | '/(coreDam)/tts-narration-requests/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/(coreDam)/users/index.vue': {
      routes:
        | '/(coreDam)/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/users/[id]/index.vue': {
      routes:
        | '/(coreDam)/users/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/users/[id]/edit.vue': {
      routes:
        | '/(coreDam)/users/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/video-shows/index.vue': {
      routes:
        | '/(coreDam)/video-shows'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/video-shows/[id]/index.vue': {
      routes:
        | '/(coreDam)/video-shows/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/video-shows/[id]/edit.vue': {
      routes:
        | '/(coreDam)/video-shows/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/video-shows/[id]/episodes/[episodeId]/index.vue': {
      routes:
        | '/(coreDam)/video-shows/[id]/episodes/[episodeId]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/video-shows/[id]/episodes/[episodeId]/edit.vue': {
      routes:
        | '/(coreDam)/video-shows/[id]/episodes/[episodeId]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/voice-families/index.vue': {
      routes:
        | '/(coreDam)/voice-families'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/voice-families/[id]/index.vue': {
      routes:
        | '/(coreDam)/voice-families/[id]'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/(coreDam)/voice-families/[id]/edit.vue': {
      routes:
        | '/(coreDam)/voice-families/[id]/edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...pathMatch].vue': {
      routes:
        | '/[...pathMatch]'
      views:
        | never
      pathParamNames:
        | 'pathMatch'
    }
    'src/pages/close-page.vue': {
      routes:
        | '/close-page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/logout.vue': {
      routes:
        | '/logout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/unauthorized.vue': {
      routes:
        | '/unauthorized'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
